name:                modbus-serve
version:             0.1.0.0
github:              "3kyro/modbus-serve"
license:             BSD3
author:              "Kyriakos Papachrysanthou"
maintainer:          "k.papachrisanthou@gmail.com"
copyright:           "2020 Kyriakos Papachrysanthou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/modbus-serve#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- iproute
- hspec
- parsec
- text
- QuickCheck
- modbus-tcp
- network
- mtl
- process
- binary
- repline
- Cabal
- either
- transformers
- directory >= 1.3.6 && < 2
- ansi-terminal >= 0.10.3 && < 1

library:
  source-dirs: src

executables:
  modbus-serve-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    - -Wall
    dependencies:
    - modbus-serve


tests:
  modbus-serve-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modbus-serve
    - hspec

