name:                modbus-client
version:             0.1.0.0
github:              "3kyro/modbus-client"
license:             BSD3
author:              "Kyriakos Papachrysanthou"
maintainer:          "k.papachrisanthou@gmail.com"
copyright:           "2020 Kyriakos Papachrysanthou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/modbus-client#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- iproute
- hspec
- parsec
- text
- QuickCheck
- modbus-tcp
- network
- mtl
- process
- binary
- repline
- Cabal
- either
- transformers
- directory
- ansi-terminal
- safe-exceptions
- aeson
- http-types
- servant-server
- wai
- warp
- stm
- tagged
- hspec-golden-aeson
- bytestring
- serialport
- exceptions
- keep-alive
- servant-client
- http-client
- random
- filepath
- turtle
library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-imports
  - -Wall

executables:
  modbus-client:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    - -Wall
    dependencies:
    - modbus-client
    - modbus-tcp


tests:
  modbus-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - modbus-client
    - hspec
    - hspec-golden-aeson  >= 0.7.0.0 && < 0.8
    - async >= 2.2 && < 2.3

